theme = "autumn_night"

[editor]
true-color = true
bufferline = "always"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.select]
"$" = "goto_line_end"
0 = "goto_line_start"

"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]


[keys.normal]
# Edit/reload helix config
"," = { o = ":config-open", r = ":config-reload", q = ":buffer-close", Q = ":buffer-close!", "," = "keep_primary_selection" }

"C-p" = ":write"

D = ["select_mode", "goto_line_end", "delete_selection"]

# Tabs
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
"A-tab" = ":new"

# Movement
0 = "goto_line_start"
"$" = "goto_line_end"

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

C-h = "goto_window_center"
C-l = "goto_window_bottom"
C-m = "goto_window_center"
 
# C-h = "select_prev_sibling"
# C-j = "shrink_selection"
# C-k = "expand_selection"
# C-l = "select_next_sibling"

# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]

[keys.insert]
j = { k = "normal_mode", j = "normal_mode" }
